version: '3.8'
services:
    ucp-smsc-sim:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '16003:16003'
        links:
            - redis
    redis:
        image: redis:5.0-alpine
